<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product')->insert([
            [
                'name' => 'Ariel Detergente Líquido',
                'sku' => 'ARL001',
                'description' => 'Detergente líquido para ropa',
                'price' => 8.50,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 1,
                'type' => 'líquido',
            ],
            [
                'name' => 'Cloralex Desinfectante',
                'sku' => 'CLX002',
                'description' => 'Desinfectante para superficies',
                'price' => 4.20,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 10,
                'type' => 'líquido',
            ],
            [
                'name' => 'Fabuloso Limpiador Multiusos',
                'sku' => 'FAB003',
                'description' => 'Limpiador multiusos de aroma lavanda',
                'price' => 5.00,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 10,
                'type' => 'líquido',
            ],
            [
                'name' => 'Pine-Sol Limpiador Multiusos',
                'sku' => 'PNS004',
                'description' => 'Limpiador multiusos con aroma de pino',
                'price' => 4.75,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 7,
                'type' => 'líquido',
            ],
            [
                'name' => 'Lysol Spray Desinfectante',
                'sku' => 'LYS005',
                'description' => 'Aerosol desinfectante',
                'price' => 6.99,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 12,
                'type' => 'aerosol',
            ],
            [
                'name' => 'Windex Limpiador de Vidrios',
                'sku' => 'WND006',
                'description' => 'Limpiador de vidrios y espejos',
                'price' => 4.00,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 6,
                'type' => 'líquido',
            ],
            [
                'name' => 'Clorox Blanqueador',
                'sku' => 'CLX007',
                'description' => 'Blanqueador líquido para ropa y superficies',
                'price' => 3.50,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 7,
                'type' => 'líquido',
            ],
            [
                'name' => 'Suavitel Suavizante de Ropa',
                'sku' => 'SUV008',
                'description' => 'Suavizante de ropa aroma fresco',
                'price' => 5.50,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 3,
                'type' => 'líquido',
            ],
            [
                'name' => 'Mr. Músculo Desengrasante',
                'sku' => 'MRM009',
                'description' => 'Desengrasante de cocina',
                'price' => 6.25,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 4,
                'type' => 'líquido',
            ],
            [
                'name' => 'Vanish Quitamanchas',
                'sku' => 'VNS010',
                'description' => 'Quitamanchas para ropa',
                'price' => 7.00,
                'status' => 'active',
                'image' => null,
                'category_id' => 2,
                'supplier_id' => 1,
                'type' => 'polvo',
            ],
            [
                'name' => 'Dove Jabón en Barra',
                'sku' => 'DVB011',
                'description' => 'Jabón en barra para cuidado personal',
                'price' => 2.20,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 2,
                'type' => 'barra',
            ],
            [
                'name' => 'Colgate Pasta Dental',
                'sku' => 'CLG012',
                'description' => 'Pasta dental para el cuidado bucal',
                'price' => 3.00,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 3,
                'type' => 'crema',
            ],
            [
                'name' => 'Pantene Shampoo',
                'sku' => 'PTN013',
                'description' => 'Shampoo para cuidado del cabello',
                'price' => 6.50,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 1,
                'type' => 'líquido',
            ],
            [
                'name' => 'Head & Shoulders Shampoo',
                'sku' => 'HS014',
                'description' => 'Shampoo anti caspa',
                'price' => 7.20,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 1,
                'type' => 'líquido',
            ],
            [
                'name' => 'Listerine Enjuague Bucal',
                'sku' => 'LST015',
                'description' => 'Enjuague bucal antiséptico',
                'price' => 5.50,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 3,
                'type' => 'líquido',
            ],
            [
                'name' => 'Gillette Espuma de Afeitar',
                'sku' => 'GLT016',
                'description' => 'Espuma de afeitar para piel sensible',
                'price' => 4.00,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 5,
                'type' => 'aerosol',
            ],
            [
                'name' => 'Axe Desodorante en Spray',
                'sku' => 'AXS017',
                'description' => 'Desodorante en aerosol aroma fresco',
                'price' => 5.20,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 2,
                'type' => 'aerosol',
            ],
            [
                'name' => 'Nivea Crema Corporal',
                'sku' => 'NVCC018',
                'description' => 'Crema corporal hidratante',
                'price' => 3.80,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 2,
                'type' => 'crema',
            ],
            [
                'name' => 'Palmolive Jabón Líquido',
                'sku' => 'PLM019',
                'description' => 'Jabón líquido para manos',
                'price' => 2.50,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 3,
                'type' => 'líquido',
            ],
            [
                'name' => 'Dial Gel Antibacterial',
                'sku' => 'DLG020',
                'description' => 'Gel antibacterial para manos',
                'price' => 2.00,
                'status' => 'active',
                'image' => null,
                'category_id' => 1,
                'supplier_id' => 6,
                'type' => 'gel',
            ],
            // Agrega los registros restantes aquí siguiendo el mismo formato...
        ]);
    }
}
